CREATE TABLE tb_category (id int8 GENERATED BY DEFAULT AS IDENTITY,
                          created_at TIMESTAMP WITHOUT TIME ZONE,
                          name varchar(255),
                          updated_at TIMESTAMP WITHOUT TIME ZONE,
                          PRIMARY KEY (id));


CREATE TABLE tb_product (id int8 GENERATED BY DEFAULT AS IDENTITY,
                         created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                         name varchar(255),
                         price numeric(19, 2),
                         updated_at TIMESTAMP WITHOUT TIME ZONE,
                         PRIMARY KEY (id));


CREATE TABLE tb_product_category (product_id int8 NOT NULL,
                                  category_id int8 NOT NULL,
                                  PRIMARY KEY (product_id,
                                               category_id));


ALTER TABLE IF EXISTS tb_product_category ADD CONSTRAINT FK5r4sbavb4nkd9xpl0f095qs2a
    FOREIGN KEY (category_id) REFERENCES tb_category;


ALTER TABLE IF EXISTS tb_product_category ADD CONSTRAINT FKgbof0jclmaf8wn2alsoexxq3u
    FOREIGN KEY (product_id) REFERENCES tb_product;

INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Jardim', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Casa', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Cozinha', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Eletrônicos', now());

INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Computador Gamer', 5000.98, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Jogo de panelas', 500.50, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Vaso de planta', 19.99, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Sofa', 1250.00, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Mouse Gamer', 200.00, now());

INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (4, 1);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (3, 2);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (1, 3);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (2, 4);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (4, 5);