version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: "products-db"
    volumes:
      - "./data/postgres:/var/lib/postgresql"
#      - "./init/data.sql:/docker-entrypoint-initdb.d/data.sql"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - db
  api:
    image: products-api
    restart: always
    container_name: products-api
    build: .
    working_dir: /products-api
    environment:
      - APP_PROFILE=dev
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
    volumes:
      - ./:/products-api
      - ~/.m2:/root/.m2
    ports:
      - "80:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - db