INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Jardim', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Casa', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Cozinha', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Eletrônicos', now());

INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Computador Gamer', 5000.98, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Jogo de panelas', 500.50, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Vaso de planta', 19.99, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Sofa', 1250.00, now());
INSERT INTO TB_PRODUCT (NAME, PRICE, CREATED_AT) VALUES ('Mouse Gamer', 200.00, now());

INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (4, 1);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (3, 2);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (1, 3);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (2, 4);
INSERT INTO TB_PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID) VALUES (4, 5);